# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_rowSums_modN <- function(x, N) {
    .Call(`_SVDNF_Cpp_rowSums_modN`, x, N)
}

Cpp_prodfun <- function(probs, filter) {
    .Call(`_SVDNF_Cpp_prodfun`, probs, filter)
}

dnorm_cpp_prod <- function(rets, mu, sig, p) {
    .Call(`_SVDNF_dnorm_cpp_prod`, rets, mu, sig, p)
}

